export const BLOCK_SIZE = 15;
export const BOARD_WIDTH = 30;
export const BOARD_HEIGHT = 40;

export const FILLED_SQUARE = 1;
export const EMPTY_SQUARE = 0;

export const PIECES = [
  [
    [FILLED_SQUARE, FILLED_SQUARE],
    [FILLED_SQUARE, FILLED_SQUARE],
  ],
  [[FILLED_SQUARE], [FILLED_SQUARE], [FILLED_SQUARE], [FILLED_SQUARE]],
  [
    [EMPTY_SQUARE, FILLED_SQUARE, FILLED_SQUARE],
    [FILLED_SQUARE, FILLED_SQUARE, EMPTY_SQUARE],
  ],
  [
    [FILLED_SQUARE, FILLED_SQUARE, EMPTY_SQUARE],
    [EMPTY_SQUARE, FILLED_SQUARE, FILLED_SQUARE],
  ],
  [
    [FILLED_SQUARE, EMPTY_SQUARE],
    [FILLED_SQUARE, EMPTY_SQUARE],
    [FILLED_SQUARE, FILLED_SQUARE],
  ],
  [
    [EMPTY_SQUARE, FILLED_SQUARE],
    [EMPTY_SQUARE, FILLED_SQUARE],
    [FILLED_SQUARE, FILLED_SQUARE],
  ],
  [
    [FILLED_SQUARE, FILLED_SQUARE, FILLED_SQUARE],
    [EMPTY_SQUARE, FILLED_SQUARE, EMPTY_SQUARE],
    [EMPTY_SQUARE, FILLED_SQUARE, EMPTY_SQUARE],
  ],
];
